# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED -Dcom.android.build.gradle.internal.uses.jdk.image.transform=false

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enables namespacing of each library's R class
android.nonTransitiveRClass=true

# Disable JDK image transform workaround for Java 21
android.experimental.jdkImageTransform=false
android.useJavaModuleSystem=false
